# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [6]:
import pandas as pd

In [7]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
insurance = pd.read_csv(url)
insurance

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [8]:
# 1.a Identify the dimensions of the dataset by determining the number of rows and columns it contains.
insurance.shape

(4008, 11)

In [9]:
# 1.b. Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
insurance.info()
insurance.dtypes
#####SUGGESTIONS
# Customer Lifetime Value: could be a float
# Number of Open Complaints: could be an integer
# ----> let's see if we can suggest other types on the following cell

<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   str
 1   ST                         1071 non-null   str
 2   GENDER                     954 non-null    str
 3   Education                  1071 non-null   str
 4   Customer Lifetime Value    1068 non-null   str
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   str
 8   Policy Type                1071 non-null   str
 9   Vehicle Class              1071 non-null   str
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 417.4 KB

Customer                         str
ST                               str
GENDER                           str
Education                        str
Customer Lifetime Value          str
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints        str
Policy Type                      str
Vehicle Class                    str
Total Claim Amount           float64
dtype: object

In [10]:
print("Unique policy type:")
print(insurance["Policy Type"].unique())

print("\nNumber of unique policy type:")
print(insurance["Policy Type"].nunique())
# We cannot set a boolean type for policy type because we have 3 types of policies.
print("\nUnique Vehicle Class:")
print(insurance["Vehicle Class"].unique())

print("\nNumber of unique Vehicle Class:")
print(insurance["Vehicle Class"].nunique())
# We cannot set a boolean type for Vehicle Class because we have 7 classes .

Unique policy type:
<ArrowStringArray>
['Personal Auto', 'Corporate Auto', 'Special Auto', nan]
Length: 4, dtype: str

Number of unique policy type:
3

Unique Vehicle Class:
<ArrowStringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car',             nan]
Length: 7, dtype: str

Number of unique Vehicle Class:
6

In [56]:
# Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
insurance.describe()
# For the Monthly Premium Auto, there are a lot of limit values; the maximum is more than 350 times larger than the median (50th percentile). 
# Also for the Montly Premium Auto, one thing that supports the last hypothesis is that the mean is double the median, which means that high values have a huge weight

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

In [57]:
insurance_state = insurance["ST"].value_counts()
state_percetage = insurance["ST"].value_counts(normalize=True) * 100
display(insurance_state, state_percetage)
# As the states aren't normalized, Washington and Arizona are duplicated

ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

ST
Oregon        29.878618
California    19.701214
Arizona       17.366947
Cali          11.204482
Nevada         9.150327
Washington     7.563025
WA             2.801120
AZ             2.334267
Name: proportion, dtype: float64

In [58]:
insurance_gender = insurance["GENDER"].value_counts()
gender_percetage = insurance["GENDER"].value_counts(normalize=True) * 100
display(insurance_gender, gender_percetage)

GENDER
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

GENDER
F         47.903564
M         43.291405
Male       4.088050
female     2.935010
Femal      1.781971
Name: proportion, dtype: float64

In [59]:
insurance_edu = insurance["Education"].value_counts()
edu_percetage = insurance["Education"].value_counts(normalize=True) * 100
display(insurance_edu, edu_percetage) 
# bachelor is repeated

Education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

Education
Bachelor                30.252101
College                 29.225023
High School or Below    27.637722
Master                   8.776844
Doctor                   3.454715
Bachelors                0.653595
Name: proportion, dtype: float64

In [60]:
insurance_policy = insurance["Policy Type"].value_counts()
policy_percetage = insurance["Policy Type"].value_counts(normalize=True) * 100
display(insurance_policy, policy_percetage) 
# The higher percentage is for personal Auto

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

Policy Type
Personal Auto     72.829132
Corporate Auto    21.848739
Special Auto       5.322129
Name: proportion, dtype: float64

In [61]:
insurance_class = insurance["Vehicle Class"].value_counts()
class_percetage = insurance["Vehicle Class"].value_counts(normalize=True) * 100
display(insurance_class, class_percetage)

Vehicle Class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

Vehicle Class
Four-Door Car    53.781513
Two-Door Car     19.140990
SUV              18.580766
Sports Car        5.322129
Luxury SUV        1.867414
Luxury Car        1.307190
Name: proportion, dtype: float64

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [66]:
# Your code here
min_state = insurance_state.sort_values(ascending=True)
display (min_state.head())

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [75]:
insurance_policy = insurance["Policy Type"].value_counts()
display(insurance_policy)
max_policy = insurance_policy.idxmax()
display (max_policy) #The first value is the highest
insurance_policy.values.argmax() # Is in position 0 or index 0

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

'Personal Auto'

np.int64(0)

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [76]:
# Personal Auto
personal_policy = insurance.loc[insurance["Policy Type"] == "Personal Auto"]
personal_policy

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
...,...,...,...,...,...,...,...,...,...,...,...
1065,XD85577,Cali,M,Bachelor,284226.69%,69417.0,73.0,1/1/00,Personal Auto,Four-Door Car,30.874869
1066,TM65736,Oregon,M,Master,305955.03%,38644.0,78.0,1/1/00,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,Cali,F,High School or Below,2031499.76%,63209.0,102.0,1/2/00,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.600000
1070,MY31220,California,F,College,899704.02%,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.600000

In [84]:
#Average income personal auto:
average_personal = personal_policy["Income"].mean()
print("The average income is: ", average_personal)

The average income is:  38180.69871794872

In [78]:
#Corporate Auto
corpo_policy = insurance.loc[insurance["Policy Type"] == "Corporate Auto"]
corpo_policy

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
12,DP39365,California,NaN,Master,879879.70%,77026.0,110.0,1/2/00,Corporate Auto,Four-Door Car,472.029737
...,...,...,...,...,...,...,...,...,...,...,...
1045,WZ31900,Oregon,F,Bachelor,864970.06%,94389.0,107.0,1/0/00,Corporate Auto,SUV,85.063708
1050,BJ53923,Arizona,M,High School or Below,260027.21%,51978.0,66.0,1/0/00,Corporate Auto,Four-Door Car,144.782152
1052,FB23788,Oregon,M,High School or Below,882883.50%,86721.0,111.0,1/0/00,Corporate Auto,SUV,532.800000
1056,PI47776,Oregon,F,Bachelor,253070.51%,89451.0,63.0,1/0/00,Corporate Auto,Four-Door Car,61.769564
1059,YG44474,Oregon,M,College,1401472.13%,54193.0,117.0,1/0/00,Corporate Auto,SUV,720.752945

In [85]:
#Average income corporate auto:
average_corpo = corpo_policy["Income"].mean()
print("The average income is: ", average_corpo)

The average income is:  41390.31196581197

In [ ]:
# People with a Corporate Auto seems to have a higher income that people with Personal Auto

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
# Your code here